from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch
from datetime import datetime
import os


def generate_report(
    file1,
    file2,
    similarity,
    token_similarity,
    ast_score,
    cfg_score,
    complexity_score,
    clone_type,
    risk,
    recommendation
):

    os.makedirs("static", exist_ok=True)

    pdf_path = os.path.join(
        "static",
        "plagiarism_report.pdf"
    )

    doc = SimpleDocTemplate(pdf_path)

    styles = getSampleStyleSheet()

    title_style = styles["Title"]
    title_style.alignment = TA_CENTER

    story = []

    # ------------------------------
    # Title
    # ------------------------------

    story.append(
        Paragraph(
            "AI Code Plagiarism Report",
            title_style
        )
    )

    story.append(Spacer(1, 12))

    # ------------------------------
    # Date & Time
    # ------------------------------

    current_time = datetime.now().strftime(
        "%d-%m-%Y %I:%M:%S %p"
    )

    story.append(
        Paragraph(
            f"<b>Generated On:</b> {current_time}",
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 12))

    # ------------------------------
    # File Names
    # ------------------------------

    story.append(
        Paragraph(
            f"<b>File 1:</b> {file1}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>File 2:</b> {file2}",
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 18))

    # ------------------------------
    # Metrics Table
    # ------------------------------

    data = [

        ["Metric", "Score"],

        ["Overall Similarity", f"{similarity:.2f}%"],

        ["Token Similarity", f"{token_similarity:.2f}%"],

        ["AST Similarity", f"{ast_score:.2f}%"],

        ["Control Flow", f"{cfg_score:.2f}%"],

        ["Complexity", f"{complexity_score:.2f}%"],

        ["Clone Type", clone_type],

        ["Risk Level", risk],

        ["Recommendation", recommendation]

    ]

    table = Table(
        data,
        colWidths=[3.2 * inch, 3.2 * inch]
    )

    table.setStyle(
        TableStyle([

            ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),

            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

            ("ALIGN", (0, 0), (-1, -1), "CENTER"),

            ("GRID", (0, 0), (-1, -1), 1, colors.black),

            ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),

            ("BOTTOMPADDING", (0, 0), (-1, 0), 10),

        ])
    )

    story.append(table)

    story.append(Spacer(1, 20))

    # ------------------------------
    # Footer
    # ------------------------------

    story.append(
        Paragraph(
            "<i>Generated by AI Code Plagiarism Checker</i>",
            styles["Italic"]
        )
    )

    doc.build(story)

    return "plagiarism_report.pdf"